apiVersion: v1
kind: Service
metadata:
  name: garage-api-service
  namespace: fiap-garage
spec:
  type: NodePort
  selector:
    app: garage-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
