apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-api
  namespace: fiap-garage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garage-api
  template:
    metadata:
      labels:
        app: garage-api
    spec:
      containers:
      - name: garage-api
        image: fiap-garage-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: fiap-garage-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fiap-garage-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: fiap-garage-secret
              key: POSTGRES_DB
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: fiap-garage-secret
              key: JWT_SECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: fiap-garage-secret
              key: JWT_REFRESH_SECRET
        - name: BREVO_API_KEY
          valueFrom:
            secretKeyRef:
              name: fiap-garage-secret
              key: BREVO_API_KEY
        - name: CRYPTO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: fiap-garage-config
              key: CRYPTO_SECRET_KEY
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: fiap-garage-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: fiap-garage-config
              key: POSTGRES_PORT
        - name: EMAIL_SENDER
          valueFrom:
            configMapKeyRef:
              name: fiap-garage-config
              key: EMAIL_SENDER
        - name: SENDER_NAME
          valueFrom:
            configMapKeyRef:
              name: fiap-garage-config
              key: SENDER_NAME
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: fiap-garage-config
              key: NODE_ENV

      volumes:
      - name: container-api
        emptyDir: {}