apiVersion: v1
kind: Service 
metadata:
  name: garage-postgres-service
  namespace: fiap-garage
spec: 
  type: ClusterIP
  selector:
    app: garage-postgres
  ports:
  - port: 5432
    targetPort: 5432