apiVersion: v1
kind: Secret
metadata:
  name: fiap-garage-secret
  namespace: fiap-garage
type: Opaque
data:
  JWT_SECRET: secret-key-1234
  JWT_REFRESH_SECRET: secret-key-1234
  NEW_RELIC_LICENSE_KEY: secret
  BREVO_API_KEY: eGtleXNpYi0xYzQ0NGViN2UxMGI5OTExM2E2YjA4YmFiNDlkYTAwM2E1YjM5YWI4Y2M3Y2M1NWM3Njg1ZDE3Y2Q5ZDY3MWNjLVNTTkVvUDNKNXFRUG5MaXQ=
  CRYPTO_SECRET_KEY: YWJj
