apiVersion: batch/v1
kind: Job
metadata:
  name: garage-seed
  namespace: fiap-garage
  annotations:
    description: "Executa seed de dados iniciais no banco de dados"
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 2  # Tenta at√© 2 vezes
  template:
    metadata:
      labels:
        app: garage-seed
    spec:
      restartPolicy: Never
      containers:
      - name: seed
        image: 451156287371.dkr.ecr.us-east-1.amazonaws.com/garagemanagement:latest
        imagePullPolicy: Always
        command: ["npm", "run", "seed:run:js"]
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: fiap-garage-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fiap-garage-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: fiap-garage-secret
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: fiap-garage-secret
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: fiap-garage-config
              key: POSTGRES_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: fiap-garage-secret
              key: JWT_SECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: fiap-garage-secret
              key: JWT_REFRESH_SECRET
        - name: BREVO_API_KEY
          valueFrom:
            secretKeyRef:
              name: fiap-garage-secret
              key: BREVO_API_KEY
        - name: CRYPTO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: fiap-garage-config
              key: CRYPTO_SECRET_KEY
        - name: EMAIL_SENDER
          valueFrom:
            configMapKeyRef:
              name: fiap-garage-config
              key: EMAIL_SENDER
        - name: SENDER_NAME
          valueFrom:
            configMapKeyRef:
              name: fiap-garage-config
              key: SENDER_NAME
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
